services:
  - type: web
    name: ppam-api
    env: node
    region: oregon
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node start-render.js
    envVars:
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        value: no-reply@ppam.org
      - key: NODE_ENV
        value: production
      - key: VAPID_PUBLIC_KEY
        value: BPK8EhomUlXsVYAtZqIMgkrSlbPLoYIKunNw_rvbypDrsARO0b3O1fLHaq7juTmrLH5Rcqq3Aoh_BrWHdDlMmuQ
      - key: VAPID_PRIVATE_KEY
        value: m1eidLn046IkMtknjAatpmnq15ztrh9c3LRhqe5SwTI
      - key: PORT
        value: "3000"
